apiVersion: v1
# k8 artifacts
kind: Service
# its own name
metadata:
  name: backend
  namespace: helloworld-ns
# deployment specs
spec:
  selector:
    tier: backend
  ports:
    # IP protocol
    - protocol: "TCP"
      # port that will be exposed by this service
      port: 80
      # port number to access on the pods targeted by the service (mapped to application)
      targetPort: 3000
      # to allow traffic inside kinD cluster
      nodePort: 30001
  # type of service
  type: NodePort