---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: certexpiry
  namespace: argocd
spec:
  destination:
    namespace: certexpiry-ns
    server: https://kubernetes.default.svc
  project: argo-learnings
  source:
    path: resources/certexpiry
    repoURL: https://github.com/cbagade/argocd-code-application-three
    targetRevision: code
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
