apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
  namespace: nodeapp-ns
  labels:
    app: nodeapp-app
spec:
  selector:
    app: nodeapp-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30006
  type: NodePort
