---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginxapp
  namespace: argocd
spec:
  destination:
    namespace: nginx-ns
    server: https://kubernetes.default.svc
  project: argo-learnings
  source:
    path: resources/nginxapp
    repoURL: https://github.com/cbagade/argocd-code-application-two
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
